### ISSUE TITLE
Does this work yet? :)

### ISSUE THREAD

**Issue by mxaddict** [voylin/GoZen#1]

**Comment by aappaapp** [comment]
No. I think these are just UI stuff?

**Comment by voylin** [comment]
@mxaddict and @aappaapp , this project just started. At this stage I'm still working on the UI and module system. I'll be uploading devlogs on my youtube channel: https://youtube.com/@voylinsgamedevjourney

This will become a video editor which is made in Godot, but a working version will probably still take a couple of months. ^^"

**Comment by mxaddict** [comment]
Thanks
