### ISSUE TITLE
Make '*.gozen' files open the GoZen editor

### ISSUE THREAD

**Issue by voylin** [voylin/GoZen#32]
I want to be able to double click on a .gozen file and it starts the editor, and skip the startup screen.

Not certain how to accomplish this yet

**Comment by aappaapp** [comment]
I think you can make an installer that registers the GoZen app to be associated with `*.gozen` files. And read the command line args like:
https://github.com/Orama-Interactive/Pixelorama/blob/eb47fa8640d8f51c01cdff54d67741a2fc1e2a4e/src/Main.gd#L190-L200

**Comment by gustavo-bordin** [comment]
Not sure if you knew but gozen means cum in portuguese, so "make gozen" is funny

**Comment by CollCaz** [comment]
This can only be done on the OS side, i think it might be possible to accomplished this using OS.execute commands, ill look into it and report what i find.

**Comment by voylin** [comment]
> This can only be done on the OS side, i think it might be possible to accomplished this using OS.execute commands, ill look into it and report what i find.

Thanks, I think OS.execute may work, but there may be permission issues with that. 

As @aappaapp pointed out, this would probably have to do through an installer.

**Comment by Kiisu-Master** [comment]
I searched for how other godot projects have done it and found these 2 commits in Pixelorama.
https://github.com/Orama-Interactive/Pixelorama/commit/0b1f0358b1d3034c5b790cdfec8523dcbacf461f
https://github.com/Orama-Interactive/Pixelorama/commit/9e7a3059f2ec92a0bfbbb892d8b8b750745ecdd0

**Comment by voylin** [comment]
This got solved with one of the local commits I have made. Only thing which needs to happen now is register "*.gozen" to the gozen_editor application and done. This is for later and is not a priority as people can associate .gozen with the correct application anyway.
