### ISSUE TITLE
The project always open in 1080

### ISSUE THREAD

**Issue by Majoramari** [voylin/GoZen#36]
### Problems or limitations

the project open in 1080p screen so its not usable in any smaller screens and you have to support these screens because this is one of the soul purpose of a "lightweight-bare minimum" video editor it should work on an old laptop... old hardware in generals

### Feature to solve the problem

make it easy to resize and open smaller than the monitor, I'm not sure but this thing built in godot

**Comment by Kiisu-Master** [comment]
you have to change the resolution that gozen opens with back to the default.
thats done in the project settings under window -> viewport width & viewport height.

**Comment by aappaapp** [comment]
I think this is more like a bug than a missing feature. I think this can be fixed by detecting monitor size and resizing it on start.

**Comment by Kiisu-Master** [comment]
> I think this is more like a bug than a missing feature. I think this can be fixed by detecting monitor size and resizing it on start.

what size would you resize it to?
resizing can look weird as the window can go off center

**Comment by aappaapp** [comment]
> what size would you resize it to?

Divided the size of the monitor by 2 (but not smaller than 600x600).

> resizing can look weird as the window can go off center

We can position the window to be at the center of the screen.

Or maybe Voylin and other people have some better ideas?

**Comment by voylin** [comment]
> > what size would you resize it to?
> 
> Divide the size of the monitor by 2 (but not smaller than 600x600).
> 
> > resizing can look weird as the window can go off center
> 
> We can position the window to be at the center of the screen.

I think this would be the best option for now. I'll look to implement it like that for now and later on look for a better solution if this would be causing any issues for people.

Most people still run 1080p monitors so having the default size to be smaller or bigger would kind of mess with UI sizing, it'll take some work to get the UI to scale correctly on different resolutions but this would also be something for later.

**Comment by Kiisu-Master** [comment]
i already quickly implemented it yesterday.
it looks weird on my small screen as the window will be minimum size

**Comment by voylin** [comment]
This has gotten fixed for now so I'll close this issue.
Got fixed with pull request #37 and got improved for working on UI in the editor with commit 81a25c7a

**Comment by voylin** [comment]
https://github.com/godotengine/godot/issues/80595
I forgot about this bug report which is probably also a part of this issue

**Comment by voylin** [comment]
I'm closing this issue for now as there is not much we can do about it for now. If this continues to be a problem in the next couple of versions of Godot/GoZen we can re-open this.
