### ISSUE TITLE
Feature: Version Checker

### ISSUE THREAD

**Issue by voylin** [voylin/GoZen#39]
Right now we are having a basic version checker which uses a json file. I'd like to improve the whole versioning system in some way that it more easily displays when you are in a dev build, a test build, or an official release. 

Not certain how to properly achieve this in a clean and effecient way yet, but I'll be working on it when I have the time, this is not a priority for now but should be in place for Version 1.0.0.

**Comment by aappaapp** [comment]
I think using GitHub API to fetch GitHub releases would be better.

**Comment by voylin** [comment]
Quick note: We should probably also have a setting to disable the update available notification. If this is disabled we don't check at all what the most recent version is.

**Comment by voylin** [comment]
Update available notification/popup will have to be implemented inside of the other modules.

Completed with  commit: 87fd87d
Added setting in commit: 0b20b5e
