### ISSUE TITLE
Color file

### ISSUE THREAD

**Issue by voylin** [voylin/GoZen#56]
We need colour files to test the timeline and media pool, but have no way of creating them.

My idea is to have a setting for a duration and a default color which is part of "media pool". Creating a new color for will give you that default color with the default set duration, double clicking will open the "file" in the effects view where you can eventually change the color with a color picker.

Possible addition would be to let the user store a certain amount of colors

**Comment by aappaapp** [comment]
My idea: Dragging it in the timeline to change its duration.

**Comment by voylin** [comment]
> My idea: Dragging it in the timeline changes its duration.

You mean that resizing the color clip in the timeline should change the duration of the color file itself and change the size in all clip instances? Or changing the duration in the timeline would change the clip size duration but not the color file duration property itself?

**Comment by aappaapp** [comment]
I meant changing the clip duration.
