### ISSUE TITLE
Include a license

### ISSUE THREAD

**Issue by Wilker-uwu** [voylin/GoZen#9]
hey!

if you're planning to make this project free for people to tinker with and share around, consider choosing a license for the program. otherwise, anything you don't explicitly allow in a license is proihibited by default, so you might wanna include something if you want to allow.

my personal bias is that, you're doing a new thing that a lot of people will benefit from, specially if you're intending to focus on having it in a small file size in the end, and Godot can also export to the web, so the [**AGPL** (v3 and later)](https://www.gnu.org/licenses/agpl-3.0.en.html) would be an awesome fit compared to the standard [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html), because on top of it implementing copyleft, it also has a case for giving the same rights to people interacting with the program over the internet (complements Godot projects being usable on the web).

[Lichess](https://github.com/lichess-org/lila/) is a project under this [license](https://github.com/lichess-org/lila/blob/master/COPYING.md), requiring anyone who publicly hosts their own version of the website to also distribute the code, while [Godot](https://docs.godotengine.org/en/stable/contributing/ways_to_contribute.html#contributing-code) itself is more permissive under the [MIT](https://github.com/godotengine/godot/blob/master/LICENSE.txt) license, but that is if you're willing to allow for components or whole derivatives of your project to be shared as proprietary / with restricted source and execution.

pick and choose what you think fits best in the project, but remember these aren't the only ones. do your research \^\^'

**Comment by voylin** [comment]
Thanks for the info! I completely forgot about selecting a license. I have been looking around quite a lot and have decided to go for the AGPL license as it is probably the best fit for this project. Thank you for suggesting that one.

I've added the License file to the project.
